version = 0.1

[default.deploy]
[default.deploy.parameters]
stack_name = "luna-code-stack"
s3_bucket = "luna-code-s3-bucket"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "luna-code-stack"
image_repositories = []
